
Epoch 1/200, Loss: 369.0437
Epoch 2/200, Loss: 362.7055
Epoch 3/200, Loss: 352.3003
Epoch 4/200, Loss: 354.0443
Epoch 5/200, Loss: 354.0265
Epoch 6/200, Loss: 354.5041
Epoch 7/200, Loss: 354.8126
Epoch 8/200, Loss: 362.2060
Epoch 9/200, Loss: 361.7816
Epoch 10/200, Loss: 355.7186
Epoch 11/200, Loss: 355.9819
Epoch 12/200, Loss: 355.0184
Epoch 13/200, Loss: 362.6595
Epoch 14/200, Loss: 359.4246
Epoch 15/200, Loss: 355.1489
Epoch 16/200, Loss: 383.7120
Epoch 17/200, Loss: 364.6455
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory