Traceback (most recent call last):
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 201, in <module>
    main()
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 190, in main
    model = DDP(model, device_ids=[local_rank])
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 625, in __init__
    self.process_group = _get_default_group()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 707, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 201, in <module>
    main()
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 190, in main
    model = DDP(model, device_ids=[local_rank])
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 625, in __init__
    self.process_group = _get_default_group()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 707, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.